source:
  url: jdbc:oracle:thin:@//192.168.147.131:1521/WECOMMIT
  username: stackoverflow2013
  password: Wecommit100x
target:
  url: jdbc:postgresql://192.168.147.130:5432/bo_dev_test_en_utf8
  username: postgres
  password: Abc12345
tables:
  - badges
workers: 4